nodes:
- input.visual:
    source: 0
- model.yolo:
    detect: ["person"]
- dabble.bbox_to_btm_midpoint
- dabble.zone_count:
    resolution: [1280, 720] # Adjust this to your camera's input resolution
    zones: [
    [[0, 0], [0.2, 0], [0.2, 0.5], [0, 0.5]],
    [[0, 0], [1, 0], [1, 1], [0, 1]],
    [[0.2, 0], [0.5, 0], [0.5, 0.5], [0.2, 0.5]],
    [[0, 0], [0.5, 0], [0.5, 0.67], [0, 0.67]]
    ]
- draw.bbox
- draw.btm_midpoint
- draw.zones
- draw.legend:
    show: ["zone_count"]
- output.screen